### ISSUE TITLE
Not able to access api.photos

### ISSUE THREAD

**Issue by xib** [picklepete/pyicloud#145] opened 2017-08-13 00:57 UTC
I installed pyicloud successfully in my raspberry pi 3.
Then I tried most commands in README directly into python interactive shell, most of them work: authentication, second-factor-authentication, devices listing, play_sound, contacts

But I was not able to access photos service:
```
>>> api.photos
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 304, in photos
    self.params
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/services/photos.py", line 30, in __init__
    params=self.params
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 469, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 67, in request
    response = super(PyiCloudSession, self).request(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
```

**Comment by ajlyakhov** [comment] 2017-08-13 13:54
+1

**Comment by bobhavlin** [comment] 2017-08-14 21:52
Same here:

```
>>> api.photos.albums
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pyicloud/base.py", line 306, in photos
    self.params
  File "/usr/lib/python2.7/site-packages/pyicloud/services/photos.py", line 35, in __init__
    params=self.params
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/pyicloud/base.py", line 67, in request
    response = super(PyiCloudSession, self).request(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='p50-photosws.icloud.com', port=443): Max retries exceeded with url: /ph/startup?clientBuildNumber=14E45&dsid=116449392&clientId=12B5D982-813A-11E7-A67B-00FF82E11130 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xff92174c>: Failed to establish a new connection: [Errno 8] Name or service not known',))
```

**Comment by hoskeri** [comment] 2017-08-22 22:40
I saw this as well, I verified that the dns record for photos does not exist, and even querying the ns servers for icloud.com directly has the same result. 

Is it possible that this service has been retired, and replaced with something else?

**Comment by chenxuefei-pp** [comment] 2017-09-08 08:59
+1
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='p26-photosws.icloud.com', port=443): Max retries exceeded with url: /ph/startup?clientBuildNumber=14E45&clientId=FDF09FAC-9471-11E7-972D-1C1B0DAE8451&dsid=1203160922 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001FA70C58208>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

**Comment by JeremyMorel** [comment] 2017-09-14 06:50
+1
{ConnectionError}HTTPSConnectionPool(host='p41-photosws.icloud.com', port=443): Max retries exceeded with url: /ph/startup?clientBuildNumber=14E45&dsid=269115202&clientId=E763E94F-9916-11E7-A69E-C4B301C10C1F (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x108f09b10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

**Comment by chenxuefei-pp** [comment] 2017-09-14 11:32
#137  can solve the problem, and now iCloud needs to use the ckdatabasews interface to get photos.

**Comment by torarnv** [comment] 2017-09-24 13:25
https://github.com/picklepete/pyicloud/pull/137 has been merged, please test

**Closed by torarnv** 2017-09-24 13:25 UTC

**Comment by Asbra** [comment] 2018-02-26 16:16
Hello. My issue seems related.
Tries to access p36-photosws.icloud.com which does not exist.
`>>> api.photos
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pyicloud\base.py", line 304, in photos
    self.params
  File "C:\Python27\lib\site-packages\pyicloud\services\photos.py", line 30, in __init__
    params=self.params
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\pyicloud\base.py", line 67, in request
    response = super(PyiCloudSession, self).request(*args, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='p36-photosws.icloud.com', port=443): Max retries exceeded with url: /ph/startup?clientBuildNumber=<my build number>&dsid=<my ds id>&clientId=<my client id> (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000007AAE518>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))`
(removed some data, lmk if they're necessary)

Can this be resolved?
