### ISSUE TITLE
Error when trying to access api.files.dir()

### ISSUE THREAD

**Issue by matbor** [picklepete/pyicloud#45] opened 2015-07-18 05:12 UTC
I can login and run the ```api.devices``` and ```api.devices[1].play_sound```, but when I try and run any of the other services like ```api.files.dir()``` I get the following errors...

```
>>> api.files.dir()
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/services/ubiquity.py", line 51, in __getattr__
    return getattr(self.root, attr)
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/services/ubiquity.py", line 47, in root
    self._root = self.get_node(0)
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/services/ubiquity.py", line 28, in get_node
    return UbiquityNode(self, request.json())
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Running python2.7.6 & requests 2.7.0

**Comment by torarnv** [comment] 2016-01-13 22:42
Duplicate of #43

**Closed** 2016-01-15 00:14 UTC

**Comment by Quentame** [comment] 2020-03-20 23:01
Seems to have the solution in #166.

Please create a new issue if still exists.
