### ISSUE TITLE
Unverified HTTPS request

### ISSUE THREAD

**Issue by dado3212** [picklepete/pyicloud#31] opened 2015-02-18 14:19 UTC
I'm getting multiple (four) InsecureRequestWarnings from urllib3 on using it with Python 2.7.6.

**Comment by coddingtonbear** [comment] 2015-02-18 15:38
This sounds like a duplicate of #30; please let me know if I'm closing this in error.

Cheers!

**Closed by coddingtonbear** 2015-02-18 15:38 UTC
