### ISSUE TITLE
`api.files.dir()` fails with JSONDecodeError

### ISSUE THREAD

**Issue by alexreg** [picklepete/pyicloud#146] opened 2017-09-02 00:10 UTC
```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    print(api.files.dir())
  File "/usr/local/lib/python3.6/site-packages/pyicloud/services/ubiquity.py", line 48, in __getattr__
    return getattr(self.root, attr)
  File "/usr/local/lib/python3.6/site-packages/pyicloud/services/ubiquity.py", line 44, in root
    self._root = self.get_node(0)
  File "/usr/local/lib/python3.6/site-packages/pyicloud/services/ubiquity.py", line 25, in get_node
    return UbiquityNode(self, request.json())
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by torarnv** [comment] 2017-09-24 13:25
Duplicate of . https://github.com/picklepete/pyicloud/issues/140

**Closed by torarnv** 2017-09-24 13:25 UTC

**Comment by Quentame** [comment] 2020-03-20 23:01
Seems to have the solution in #166.

Please create a new issue if still exists.
